crud/books/urls.py
from django.conf.urls import url

from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='book_list'),
    url(r'^books/create/$', views.book_create, name='book_create'),
    url(r'^books/(?P<pk>\d+)/update/$', views.book_update, name='book_update'),
    url(r'^books/(?P<pk>\d+)/delete/$', views.book_delete, name='book_delete'),
]

crud/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('crud.books.urls')),
    url(r'^admin/', admin.site.urls),
]

crud/books/models.py
from django.db import models

class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    pub_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

crud/books/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'pub_date', 'author', 'price', 'pages', 'book_type', )

crud/books/views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import Book
from .forms import BookForm


class IndexView(generic.ListView):
    template_name = 'books/book_list.html'
    queryset = Book.objects.all()


def save_book_form(request, form, template_name):
    data = dict()

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            book_list = Book.objects.all()
            data['html_book_list'] = render_to_string(
                'books/includes/partial_book_list.html',
                { 'book_list': book_list },
            )
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(
        template_name,
        context,
        request=request,
    )

    return JsonResponse(data)


def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
    else:
        form = BookForm()

    return save_book_form(request, form, 'books/includes/partial_book_create.html')


def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
    else:
        form = BookForm(instance=book)

    return save_book_form(request, form, 'books/includes/partial_book_update.html')


def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    data = dict()

    if request.method == 'POST':
        book.delete()
        data['form_is_valid'] = True
        book_list = Book.objects.all()
        data['html_book_list'] = render_to_string(
            'books/includes/partial_book_list.html',
            { 'book_list': book_list },
        )
    else:
        context = {'book': book}
        data['html_form'] = render_to_string(
            'books/includes/partial_book_delete.html',
            context,
            request=request,
        )

    return JsonResponse(data)

crud/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>CRUD - Bookstore</title>
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicon/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicon/apple-touch-icon-114x114.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block stylesheet %}{% endblock %}
</head>
<body>
    {% include 'header.html' %}

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

crud/templates/books/book_list.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}
    <script src="{% static 'books/js/books.js' %}"></script>
{% endblock %}

{% block content %}
    <h1 class="page-header">Books</h1>
    <p>
        <button type="button"
                class="btn btn-primary js-create-book"
                data-url="{% url 'books:book_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        New book
        </button>
    </p>
    <table class="table" id="book-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Author</th>
                <th>Type</th>
                <th>Publication date</th>
                <th>Pages</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% include 'books/includes/partial_book_list.html' %}
        </tbody>
    </table>
    <div class="modal fade" id="modal-book">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
    </div>
{% endblock %}

crud/templates/books/includes/partial_book_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'books:book_create' %}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new book</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create book</button>
  </div>
</form>

crud/templates/books/includes/partial_book_delete.html
<form method="post" action="{% url 'books:book_delete' book.id %}" class="js-book-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Confirm book deletion</h4>
    </div>
    <div class="modal-body">
        <p class="lead">Are you sure you want to delete the book <strong>{{ book.title }}</strong>?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete book</button>
    </div>
</form>

crud/templates/books/includes/partial_book_form.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}

crud/templates/books/includes/partial_book_list.html
{% for book in book_list %}
    <tr>
        <td>{{ book.id }}</td>
        <td>{{ book.title }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.get_book_type_display }}</td>
        <td>{{ book.pub_date }}</td>
        <td>{{ book.pages }}</td>
        <td>{{ book.price }}</td>
        <td>
            <button type="button"
                    class="btn btn-warning btn-sm js-update-book"
                    data-url="{% url 'books:book_update' book.id %}">
            <span class="glyphicon glyphicon-pencil"></span> Edit
            </button>
            <button type="button"
                    class="btn btn-danger btn-sm js-delete-book"
                    data-url="{% url 'books:book_delete' book.id %}">
            <span class="glyphicon glyphicon-trash"></span> Delete
            </button>
        </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="8" class="text-center bg-warning">No book</td>
    </tr>
{% endfor %}

crud/templates/books/includes/partial_book_update.html
<form method="post" action="{% url 'books:book_update' form.instance.pk %}" class="js-book-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Create a new book</h4>
    </div>
    <div class="modal-body">
        {% include 'books/includes/partial_book_form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Update book</button>
    </div>
</form>

crud/templates/header.html
<header>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'books:book_list' %}">
                    <span>CRUD</span>
                </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>
</header>